version: "3.9"

services:
  db:
    container_name: ft_transcendence
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}