version: '3.8'

services:
  web:
    build: ./app
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis  # Aggiungi questa dipendenza

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:  # Aggiungi il servizio Redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
