version: '3.8'

services:
  web:
    build: ./app
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
            cp -r /usr/src/app/staticfiles/ /home/app/web/ &&
            python manage.py migrate &&
            gunicorn ft_transcendence.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
        - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  uvicorn:
    build: ./app
    command: uvicorn ft_transcendence.asgi:application --host 0.0.0.0 --port 9000 --workers 8
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
        - 9000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:  # Aggiungi il servizio Redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
