# Generated by Django 4.2.7 on 2023-12-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_winner', models.IntegerField()),
                ('score_loser', models.IntegerField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('profile_loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='core.profile')),
                ('profile_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='core.profile')),
            ],
        ),
    ]
